# Generated by Django 2.2.7 on 2020-01-15 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acompanantes',
            fields=[
                ('Id_Acomp', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Acomp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='areastrabajo',
            fields=[
                ('Id_Area', models.AutoField(primary_key=True, serialize=False)),
                ('NombreArea', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='edocivil',
            fields=[
                ('Id_EdoCivil', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_EdoCivil', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='metanticonceptivos',
            fields=[
                ('Id_Metodo', models.AutoField(primary_key=True, serialize=False)),
                ('NombreMetodo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='pacientes',
            fields=[
                ('Nombre_Pac', models.CharField(max_length=50)),
                ('Apellidos_Pac', models.CharField(max_length=50, null=True)),
                ('FechaNac', models.DateField()),
                ('Peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Talla', models.DecimalField(decimal_places=2, max_digits=3)),
                ('CURP', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('Telefono', models.IntegerField()),
                ('Sexo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='tipoconsultas',
            fields=[
                ('Id_TipoConsulta', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_TipoConsulta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='valoraciontanner',
            fields=[
                ('Id_ValTanner', models.AutoField(primary_key=True, serialize=False)),
                ('Img_ValTanner', models.ImageField(null=True, upload_to='images/tanner')),
                ('NombreValTanner', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('Nombre', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=50)),
                ('Mail', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Telefono', models.IntegerField()),
                ('Id_Area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.areastrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='expedientes',
            fields=[
                ('Id_Exped', models.AutoField(primary_key=True, serialize=False)),
                ('CURP', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.pacientes')),
            ],
        ),
        migrations.CreateModel(
            name='domicilios',
            fields=[
                ('Id_Domicilio', models.AutoField(primary_key=True, serialize=False)),
                ('Calle', models.CharField(max_length=100)),
                ('NumInt', models.IntegerField(default=0)),
                ('NumExt', models.IntegerField(default=0)),
                ('Colonia', models.CharField(max_length=75)),
                ('CP', models.IntegerField()),
                ('Municipio', models.CharField(max_length=100)),
                ('Estado', models.CharField(max_length=50)),
                ('CURP', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.pacientes')),
            ],
        ),
        migrations.CreateModel(
            name='consultagral',
            fields=[
                ('FolioConsulta', models.AutoField(primary_key=True, serialize=False)),
                ('FechaConsulta', models.DateTimeField()),
                ('CURP', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.pacientes')),
                ('Id_Acomp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.acompanantes')),
                ('Id_Exped', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.expedientes')),
                ('Id_TipoConsulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.tipoconsultas')),
                ('Mail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='antfamiliares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grado', models.CharField(max_length=50)),
                ('EdadPadre', models.IntegerField(default=0)),
                ('EdadMadre', models.IntegerField(default=0)),
                ('EscPadre', models.CharField(max_length=50)),
                ('EscMadre', models.CharField(max_length=50)),
                ('FolioConsulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.consultagral')),
            ],
        ),
        migrations.CreateModel(
            name='antescolares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grado', models.CharField(max_length=50)),
                ('Promedio', models.DecimalField(decimal_places=2, max_digits=3)),
                ('RepitioGrado', models.BooleanField()),
                ('DesercionEsc', models.BooleanField()),
                ('Causa_DesercionEsc', models.CharField(max_length=250)),
                ('ConflictProf', models.BooleanField()),
                ('Causa_ConflictProf', models.CharField(max_length=250)),
                ('RelacionComp', models.CharField(max_length=250)),
                ('TrabajoAnt', models.BooleanField()),
                ('Obs_TrabajoAnt', models.CharField(max_length=250)),
                ('TrabajoActual', models.BooleanField()),
                ('FolioConsulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.consultagral')),
            ],
        ),
    ]
