# Generated by Django 2.2.7 on 2020-01-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20200115_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='Telefono',
            field=models.CharField(max_length=10),
        ),
    ]
