# Generated by Django 2.2.6 on 2020-05-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20200218_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultagral',
            name='Mail',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='usuarios',
        ),
    ]
