# Generated by Django 2.2.6 on 2020-05-09 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20200509_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultagral',
            old_name='Mail',
            new_name='UserID',
        ),
    ]
